version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: on-failure
    env_file:
      - .env
    networks:
      - tracking-network

  trackingapp:
    build: .
    restart: on-failure
    env_file:
      - .env
    networks:
      - tracking-network

  mongodb:
    restart: unless-stopped
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    networks:
      - tracking-network
networks:
  tracking-network:
    driver: bridge
