version: "3"
services:
  app:
    build: .
    ports:
      - 8080:8080
      # - $PORT:$PORT
    restart: on-failure
    env_file:
      - .env
    # networks:
    #   - mongo-network

  mongodb:
    restart: unless-stopped
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
